obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.2
inflation_radius: 0.55
footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]
footprint_padding: 0.01

# Obstacle and raytrace configuration
observation_sources: scan
scan:
  sensor_frame: laser_link_v1_1
  data_type: LaserScan
  topic: /scan
  marking: true
  clearing: true

# Layer configuration
plugins:
  - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

