local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  width: 5.0
  height: 5.0
  resolution: 0.05
  static_map: false
  rolling_window: true
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  obstacle_layer:
    observation_sources: scan
    scan: {sensor_frame: laser_link_v1_1, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
  inflation_layer:
    inflation_radius: 0.55

