TebLocalPlannerROS:
  # Robot configuration
  max_vel_x: 0.5
  max_vel_x_backwards: 0.2  # Enable backward movement
  max_vel_theta: 0.3
  acc_lim_x: 0.5
  acc_lim_theta: 0.8

  # Goal tolerance parameters
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  free_goal_vel: true

  # Trajectory configuration parameters
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: true
  allow_init_with_backwards_motion: true

  # Obstacle configuration parameters
  min_obstacle_dist: 0.2  # Distance to obstacles
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30

  # Optimization parameters
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: true
  optimization_verbose: false
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_dynamic_obstacle: 10  # not in use yet

  # Misc
  footprint_model:
    type: "point"
    radius: 0.2  # should match the robot_radius in costmap configuration
  map_frame: /map

